/** Utility file for nba-salary-cap constants. */

/** Map of each team name to its team code. */
export const teamNameToCode = new Map<string, string>([
  ['Atlanta Hawks', 'ATL'],
  ['Brooklyn Nets', 'BKN'],
  ['Boston Celtics', 'BOS'],
  ['Charlotte Hornets', 'CHA'],
  ['Chicago Bulls', 'CHI'],
  ['Cleveland Cavaliers', 'CLE'],
  ['Dallas Mavericks', 'DAL'],
  ['Denver Nuggets', 'DEN'],
  ['Detroit Pistons', 'DET'],
  ['Golden State Warriors', 'GSW'],
  ['Houston Rockets', 'HOU'],
  ['Indiana Pacers', 'IND'],
  // Clippers are represented using both.
  ['LA Clippers', 'LAC'],
  ['Los Angeles Clippers', 'LAC'],
  ['Los Angeles Lakers', 'LAL'],
  ['Memphis Grizzlies', 'MEM'],
  ['Miami Heat', 'MIA'],
  ['Milwaukee Bucks', 'MIL'],
  ['Minnesota Timberwolves', 'MIN'],
  ['New Orleans Pelicans', 'NOP'],
  ['New York Knicks', 'NYK'],
  ['Oklahoma City Thunder', 'OKC'],
  ['Orlando Magic', 'ORL'],
  ['Philadelphia 76ers', 'PHI'],
  ['Phoenix Suns', 'PHX'],
  ['Portland Trail Blazers', 'POR'],
  ['Sacramento Kings', 'SAC'],
  ['San Antonio Spurs', 'SAS'],
  ['Toronto Raptors', 'TOR'],
  ['Utah Jazz', 'UTH'],
  ['Washington Wizards', 'WAS'],
]);
